### ISSUE TITLE
STP_Detect doesn't return a value at the end of function

### ISSUE THREAD

**Issue by emoon** [l29ah/ayfly#6]
When I build the code I get this warning (along with a bunch of other ones as I build with `-Wall`)

```
ayfly/src/libayfly/players/STPPlay.h:410:1: warning: control reaches end of non-void function [-Wreturn-type]
```

https://github.com/l29ah/ayfly/blob/master/src/libayfly/players/STPPlay.h#L342

**Comment by l29ah** [comment]
I've fixed it purely from inferring the code functionality from the context, as i don't know where to find such exotic files to test with.

**Comment by emoon** [comment]
Yeah same, but better to be on the safe side and return false as you did instead of having undefined behaviour if someone for whatever reason would end up there.

**Comment by l29ah** [comment]
Okay, found some old music from n1ko, and it seems working fine.
